### ISSUE TITLE
[Bug] Unable to use containers for WorldmapView.

### ISSUE THREAD

**Issue by Abab-bk** [don-tnowe/godot-worldmap-builder#1]
I noticed WorldmapView extends from Control, but if I add a WorldmapView node under any container, it will be misaligned. Is this a bug?
Additionally, it seems adding nodes using GDScript is somewhat difficult now. Have you considered adding more features to enhance adding nodes with GDScript?

Finally, thank you for your hard work!

**Comment by don-tnowe** [comment]
Ah, it's setting its rect to enclose all nodes so it's not hidden when off-screen, but it works wrong because it expects to be under a `Node2D`. Will fix.

Will track the latter suggestion in #2, thanks.

**Comment by don-tnowe** [comment]
Should work now on `main` branch. Was a quick fix.
