### ISSUE TITLE
`WorldmapView` sometimes does not update its rect when a node is created or moved

### ISSUE THREAD

**Issue by Abab-bk** [don-tnowe/godot-worldmap-builder#7]
Below is a video, but when I move the camera in the example scene, such a bug does not occur. I speculate that it is because the "size" of my scene is too large.

https://github.com/don-tnowe/godot-worldmap-builder/assets/55276676/bebc2de6-85d2-4934-8f08-e6e724f32a6f

You need to download video to watch, recording full size video is too big.
The tree disappeared because I moved the camera.

**Comment by don-tnowe** [comment]
Before, it didn't stretch its rect to fit all nodes. I changed it to do that (*so it doesn't disappear like that, and also works in containers*) but might still not work sometimes.

- Do skill tree nodes get added at runtime?
- Is selecting the `WorldmapView` itself show a rectangle that fits all nodes? Does moving nodes outside expand the rectangle?
- What's the view's parent node?

**Comment by Abab-bk** [comment]
> Before, it didn't stretch its rect to fit all nodes. I changed it to do that (_so it doesn't disappear like that, and also works in containers_) but might still not work sometimes.
> 
> * Do skill tree nodes get added at runtime?
> * Is selecting the `WorldmapView` itself show a rectangle that fits all nodes? Does moving nodes outside expand the rectangle?
> * What's the view's parent node?

> Do skill tree nodes get added at runtime?

Yes, but only once.

> Is selecting the WorldmapView itself show a rectangle that fits all nodes? Does moving nodes outside expand the rectangle?

Not in the editor. I don't know how to debug in game running.

> What's the view's parent node?

Node. But the node is a child of SubViewport, the SubViewport is a child of SubViewportContainer.

**Comment by Abab-bk** [comment]
"Yes, but only once." means that I only performed the operation of adding a skill tree node once. However, I did use the latest version, but I indeed did not modify the rectangle in the editor.

https://github.com/don-tnowe/godot-worldmap-builder/assets/55276676/88ed34ed-8aa8-42e8-9d8d-f593c88f6dbc

**Comment by don-tnowe** [comment]
Notices the issue.

You have `Auto Minsize` disabled.
